MVC/CI-Platform-solution/CI-Platform/Controllers/PlatformController.cs
using CI_Platform.Entities.Models;
using CI_Platform.Entities.ViewModels;
using CI_Platform.Repository.Interface;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CI_Platform.Controllers
{
    
    public class PlatformController : Controller
    {
        public readonly IPlatformRepository _platform;
        public readonly IVolunteerRepository _volunteer;
        public readonly IStoryRepository _story;


        public PlatformController(IPlatformRepository platform, IVolunteerRepository volunteer, IStoryRepository story)
        {

            //_userRepository = userRepository;
            _platform = platform;
            _volunteer = volunteer;
            _story = story;

        }

        [HttpGet]

        [Authorize]
        public IActionResult PlatformLandingPage()
        {
            string name = HttpContext.Session.GetString("Uname");
            ViewBag.Uname = name;

            //ViewBag.City = _platform.GetCitys();

            List<Mission> missionDeails = _platform.GetMissionDetails();
            ViewBag.MissionDeails = missionDeails;

            ViewBag.cont = missionDeails.Count;

            var UId = (int)HttpContext.Session.GetInt32("UId");
            ViewBag.uid = UId;

            List<City> Cities = _platform.GetCitys();
            ViewBag.Cities = Cities;
            List<Country> Countries = _platform.GetCountry();
            ViewBag.Countries = Countries;
            List<MissionTheme> Themes = _platform.GetMissionTheme();
            ViewBag.Themes = Themes;
            List<MissionSkill> Skills = _platform.GetSkills();
            ViewBag.Skills = Skills;



            PlatformModel ms = _platform.GetMissions();


            return View(ms);
        }
        public IActionResult Filter(List<int>? cityId, List<int>? countryId, List<int>? themeId, List<int>? skillId, string? search, int? sort, int PageIndex = 1)
        {
            List<Mission> cards = _platform.Filter(cityId, countryId, themeId, skillId, search, sort);

            var UId = (int)HttpContext.Session.GetInt32("UId");
            ViewBag.uid = UId;

            if (cards.Count == 0)
            {
                return PartialView("_NoMissionFound");
            }

            int PageSize = 3;

            int TotalRecords = (int)Math.Ceiling(cards.Count() / (double)PageSize);
            ViewBag.cont = cards.Count;
            List<Mission> records = cards.Skip((PageIndex - 1) * PageSize).Take(PageSize).ToList();



            PlatformModel platformModel = new PlatformModel();
            {
                platformModel.Mission = records;
                platformModel.totalcount = TotalRecords;
            }


            
            return PartialView("_FilterMissionPartial", platformModel);


        }
        public bool AddFav(int MissionId)
        {

            int UId = (int)HttpContext.Session.GetInt32("UId");

            bool favorite = _platform.AddFav(UId, MissionId);

            return favorite;



            //return RedirectToAction("PlatformLandingPage", "Home");
        }



        [Authorize]
        public IActionResult Volunteering_Mission(int mid, int pageIndex = 1)
        {


            string name = HttpContext.Session.GetString("Uname");
            ViewBag.Uname = name;

            if (name != null)
            {
                var UId = (int)HttpContext.Session.GetInt32("UId");
                ViewBag.uid = UId;


                VolunteerModel volunteerModel = _volunteer.DisplayModel(mid, pageIndex);

                var rating = volunteerModel.mission.MissionRatings.FirstOrDefault(x => x.UserId == UId && x.MissionId == mid);
               
                if (rating != null)
                {
                    ViewBag.rating = rating.Rating;
                }
                ViewBag.rating = 0;
                int pageSize = 2;
                volunteerModel.volunteres = _volunteer.recentVolunteers(mid);
                volunteerModel.totalPage = (int)Math.Ceiling(volunteerModel.volunteres.Count() / (double)pageSize);
                volunteerModel.volunteres = volunteerModel.volunteres.Skip((pageIndex - 1) * 2).Take(2).ToList();
                return View(volunteerModel);
            }
            return View();
        }

        public IActionResult recentVolunteers(int mid, int pageIndex = 1)
        {
            int pageSize = 2;
            VolunteerModel vm = _volunteer.DisplayModel(mid, pageIndex); ;
            vm.volunteres = _volunteer.recentVolunteers(mid);
            vm.totalPage = (int)Math.Ceiling(vm.volunteres.Count() / (double)pageSize);
            vm.volunteres = vm.volunteres.Skip((pageIndex-1)*pageSize).Take(pageSize).ToList();

            return PartialView("_RecentVolunteers",vm);
        }

        public void AddComment(int obj, string comnt)
        {

            int UserId = (int)HttpContext.Session.GetInt32("UId");
            bool comntAdded = _volunteer.addComment(obj, UserId, comnt);
            if (comntAdded)
            {
                ViewBag.ComntAdded = "Comment Added";
            }
            else
            {
                ViewBag.ComntAdded = "Comment not Added";
            }

        }



        [HttpPost]
        public bool applyMission(int missionId)
        {
            int UserId = (int)HttpContext.Session.GetInt32("UId");
            var apply = _volunteer.applyMission(missionId, UserId);
            if (apply == true)
            {
                //TempData["success"] = "Applied Successfully...";
                return apply;
            }
            //TempData["error"] = "You've already Applied... ";
            return false;
        }


        public void RecommandToCoWorker(List<int> toUserId, int mid)
        {
            int FromUserId = (int)HttpContext.Session.GetInt32("UId");

            _volunteer.RecommandToCoWorker(FromUserId, toUserId, mid);



        }

        //Star Rating
        public JsonResult MissionRating(int mid, int rating)
        {
            int userId = (int)HttpContext.Session.GetInt32("UId");
            bool success = _volunteer.MissionRating(userId, mid, rating);
            return Json(success);
        }

        //public IActionResult Index()
        //{
        //    return View();
        //}
    }
}

MVC/CI-Platform-solution/CI-Platform/Views/Shared/_Layout.cshtml
﻿
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - CI_Platform</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
       <link href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/style.css" asp-append-version="true" />
          <script src="~/lib/jquery/dist/jquery.min.js"></script>
<script src="//cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/toastr.min.js"></script>

</head>
<body>

   
    <div class="container">
        <nav class="navbar navbar-expand-lg bg-body-tertiary">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"><i class="bi bi-menu-button-wide"></i></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav me-auto mb-2 mb-lg-0 topbar">

                        <li class="nav-item ">
                            <a class="nav-link text-dark" asp-action="StoryListing" asp-controller="Story">Stories</a>

                        </li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Policy
                            </a>
                            <ul class="dropdown-menu">
                                <li><a class="dropdown-item" href="#">Action</a></li>
                                <li><a class="dropdown-item" href="#">Another action</a></li>
                                <li>
                                    <hr class="dropdown-divider">
                                </li>
                                <li><a class="dropdown-item" href="#">Something else here</a></li>
                            </ul>
                        </li>

                    </ul>

                </div>
                <div class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle " href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        @{
                            String avtar = @User.Claims.FirstOrDefault(m => m.Type == "Avtar").Value;
                        }
                        <img src="~/img/@avtar" class="profile-nav" alt=""> @ViewBag.Uname
                       @* @User.Claims.FirstOrDefault(m=>m.Type == "Name").Value*@
                    </a>
                    <ul class="dropdown-menu me-5">
                        <li><a class="dropdown-item" asp-action="PlatformLandingPage" asp-controller="Platform">Home</a></li>
                        <li><a class="dropdown-item" asp-action="UserProfile" asp-controller="Profile">Profile</a></li>
                        <li><a class="dropdown-item" asp-action="TimeSheet" asp-controller="Profile">Volunteering Timesheet</a></li>
                       @{
                            String role = @User.Claims.FirstOrDefault(m => m.Type == "role").Value;
                        }
                        @if (role == "Admin")
                        {
                            <li><a class="dropdown-item" asp-action="AdminMain" asp-controller="Admin">Admin Acess</a></li>
                         }
                        <li>
                            <hr class="dropdown-divider">
                        </li>
                        <li><a class="dropdown-item" asp-action="LogOut" asp-controller="User">Log out</a></li>
                    </ul>
                </div>
            </div>
        </nav>
       @* <div class="row  border-top border-bottom">
            <div class="col-6 ">
                <form class="d-flex mt-md-3" role="search">
                    <i class="bi bi-search mt-2 ms-2"></i>
                    <input class="form-control border-white" type="search" placeholder="Search Mission " aria-label="Search" id="searchb" onkeyup="temp()">
                </form>
            </div>
            <div class="col-6 ">
                <button class="btn btn-primary d-md-none w-100" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
                    Filter Missions
                </button>
                </p>
                <div class="collapse d-md-flex " id="collapseExample">
                    <select class="form-select  border-white xyz" aria-label="Default select example" placeholder="Country" id="countryId" onchange="temp(); GetCity();">
                        <option selected>Country</option>
                        @foreach (var item in @ViewBag.Countries)
                        {

                            <option value="@item.CountryId"> @item.Name</option>
                        }
                    </select>
                    <select class="form-select border-white xyz " aria-label="Default select example" id="selectCityList" onchange="temp()">
                     *@ 
                       @*     <a class="nav-link  text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            City
                        </a>*@
                      @*  <ul class="dropdown-menu">
                        @foreach (var item in ViewBag.Cities)
    {
                        <li><input type="checkbox" name="Cities" value="@item.CityId" />
                        @item.Name
                        </li>*@
@*    }*@
                         @*   <option selected>City</option>
                          @foreach (var item in @ViewBag.Cities)
                            {

                            <option value="@item.CityId"> @item.Name</option>
                            }*@
                           @* </ul>*@
                   @* </select>
                    <div class="form-select border-white xyz" aria-label="Default select example" id="theme" onchange="temp()">
                        <a class="nav-link  text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Themes
                        </a>
                        <ul class="dropdown-menu">

                            @foreach (var item in @ViewBag.Themes)
                            {

                                <li><input type="checkbox" value="@item.MissionThemeId" /> @item.Title </li>
                            }
                            </ul>
                    </div>
                    <div class="form-select  border-white xyz" aria-label="Default select example" id="skill" onchange="temp()">

                        <a class="nav-link  text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Skills
                        </a>
                        <ul class="dropdown-menu">

                            @foreach (var item in @ViewBag.Skills)
                            {

                                <li><input type="checkbox" value="@item.SkillId" /> @item.Skill.SkillName </li>
                            }*@
                            @*
                                <option selected>Skills</option>
                                @foreach (var item in @ViewBag.Skills)
                                {

                                <option value="1"> @item.SkillName</option>
                                }*@
@*
                    </div>
                </div>


            </div>
        </div>*@
    </div>


    <hr class="m-0" />

    <!--.............Page Body..............-->
    
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
   

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - CI_Platform - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>

             <button class="border-0 p-0 btn btn-primary" style="background-color: white;"
                            data-toggle="modal" data-target="#exampleModal1">
                        <span><a href="#" style="color: #333333;">Contact Us</a></span>
                    </button>
                    <div class="modal fade" id="exampleModal1" tabindex="-1" role="dialog"
                         aria-labelledby="exampleModalLabel" aria-hidden="true">
                        <div class="modal-dialog" role="document">
                            <div class="modal-content">
                                <div class="modal-header">
                                    <h5 class="modal-title" id="exampleModalLabel">Contact Us</h5>
                                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                        <span aria-hidden="true">&times;</span>
                                    </button>
                                </div>
                                <div class="modal-body">
                                    @*   <form>*@
                                    <label>Name*</label>
                                    <input type="text" id="Name" class="form-control" placeholder="Enter your name">
                                    <label class="mt-3">Email Address*</label>
                                    <input type="text" id="Email" class="form-control" placeholder="Enter your Email Address">
                                    <label class="mt-3">Subject*</label>
                                    <input type="text" id="Subject" class="form-control" placeholder="Enter your Subject">
                                    <label class="mt-3" for="exampleFormControlTextarea1">Message*</label>
                                    <textarea class="form-control" id="Message" rows="4"
                                              placeholder="Enter your message..."></textarea>
                                    @*      </form>*@
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                                    <button type="button" class="btn btn-primary" onclick="ContactUs()">Save changes</button>
                                </div>
                            </div>
                        </div>
                    </div>

        </div>
    </footer>



 
                    
       <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script> 
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)

</body>
</html>

MVC/CI-Platform-solution/CI-Platform/Views/Shared/nav2.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@

<div class="row">
    <div class="col-6 ">
        <form class="d-flex mt-md-3" role="search">
            <i class="bi bi-search mt-2 ms-2"></i>
            <input class="form-control border-white" type="search" placeholder="Search Mission " aria-label="Search" id="searchb" onkeyup="temp(1); ">
        </form>
    </div>
    <div class="col-6 ">
        <button class="btn btn-primary d-md-none w-100" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
            Filter Missions
        </button>

        <div class="collapse d-md-flex " id="collapseExample">
            <div class="form-select  border-white xyz" aria-label="Default select example" placeholder="Country" id="countryId" onchange="temp(1); filterBadges(); GetCity();">
                @*<option selected>Country</option>
                @foreach (var item in @ViewBag.Countries)
                {

                    <option value="@item.CountryId"> @item.Name</option>
                }*@

                <a class="nav-link  text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Country
                </a>
                <ul class="dropdown-menu">

                    @foreach (var item in @ViewBag.Countries)
                    {

                        <li><input type="checkbox" class="country_@item.CountryId" name="country" id="@item.Name" value="@item.CountryId" /> @item.Name </li>
                    }
                </ul>
            </div>
            <div class="form-select border-white xyz " aria-label="Default select example"  onchange="temp(1); filterBadges();">

                     <a class="nav-link  text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    City
                    </a>
                  <ul class="dropdown-menu" id="selectCityList">
                    @foreach (var item in @ViewBag.Cities)
                    {
                    <li><input type="checkbox" class="city_@item.CityId" name="city" id="@item.Name" value="@item.CityId" />
                    @item.Name
                    </li>
                    }
               @* <select>
                <option selected>City</option>
                @foreach (var item in @ViewBag.Cities)
                {

                    <option value="@item.CityId"> @item.Name</option>
                }
                
               </select>*@
                </ul>
            </div>
            <div class="form-select border-white xyz" aria-label="Default select example" id="theme" onchange="temp(1); filterBadges();">
                <a class="nav-link  text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Themes
                </a>
                <ul class="dropdown-menu">

                    @foreach (var item in @ViewBag.Themes)
                    {

                        <li><input type="checkbox" class="theme_@item.MissionThemeId" name="theme" id="@item.Title" value="@item.MissionThemeId" /> @item.Title </li>
                    }
                </ul>
            </div>
            <div class="form-select  border-white xyz" aria-label="Default select example" id="skill" onchange="temp(1); filterBadges();">

                <a class="nav-link  text-dark" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Skills
                </a>
                <ul class="dropdown-menu">

                    @foreach (var item in @ViewBag.Skills)
                    {

                        <li><input type="checkbox" class="skill_@item.SkillId" id="@item.Skill.SkillName" name="skill" value="@item.SkillId" /> @item.Skill.SkillName </li>
                    }
                </ul>
                @*
                    <option selected>Skills</option>
                    @foreach (var item in @ViewBag.Skills)
                    {

                    <option value="1"> @item.SkillName</option>
                    }*@

            </div>
        </div>


    </div>
</div>

<hr class="m-0" />